# Generated by Django 3.1.4 on 2021-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210129_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporallink',
            name='email_request',
            field=models.CharField(default='', max_length=100),
        ),
    ]
